repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv --project labs run ruff check --fix
        language: system
        types: [python]
        files: ^labs/
        require_serial: true
      - id: black
        name: black
        entry: uv --project labs run black
        language: system
        types: [python]
        files: ^labs/
        require_serial: true
